---
version: "3.9"

services:
  sanctions_build:
    build:
      context: .
      dockerfile: docker/opensanctions/zavod/Dockerfile
    volumes:
      - sanctions_data:/data
    profiles:
      - builder

  sanctions_core:
    image: ghcr.io/opensanctions/yente:latest
    restart: unless-stopped
    environment:
      YENTE_INDEX_URL: http://elasticsearch:9200
      YENTE_DATA_PATH: /data/export.tar.gz
      YENTE_SCHEDULE: "0 */6 * * *"
      YENTE_AUTO_REINDEX: "true"
    volumes:
      - sanctions_data:/data:ro
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  graphsense_api:
    image: graphsense/graphsense-api:latest
    depends_on:
      - redis
    volumes:
      - keyspace-data:/var/lib/graphsense

  graphsense_ingest:
    image: graphsense/graphsense-ingest:latest
    volumes:
      - keyspace-data:/var/lib/graphsense

  puppeteer_srv:
    build: ./docker/puppeteer
    shm_size: "1gb"
    environment:
      PUPPETEER_HEADLESS: "true"
      REDIS_URL_FILE: /run/secrets/redis_url
      SERVICE_TOKEN_FILE: /run/secrets/puppeteer_service_token
    secrets:
      - redis_url
      - puppeteer_service_token

  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    environment:
      SANCTIONS_URL: http://sanctions_core:8000
      CRYPTO_URL: http://graphsense_api:8000
      WEB_URL: http://puppeteer_srv:7000
      API_KEYS_FILE: /run/secrets/api_gateway_keys
      REDIS_URL_FILE: /run/secrets/redis_url
      WEB_TOKEN_FILE: /run/secrets/puppeteer_service_token
    depends_on:
      - sanctions_core
      - graphsense_api
      - puppeteer_srv
    secrets:
      - api_gateway_keys
      - redis_url
      - puppeteer_service_token

  redis:
    image: redis:7
    entrypoint:
      - "sh"
      - "-c"
    command: >-
      REDIS_PASSWORD="$(cat /run/secrets/redis_password)";
      redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
      --requirepass "$REDIS_PASSWORD"
    volumes:
      - redis-data:/data
    secrets:
      - redis_password

volumes:
  sanctions_data:
  es-data:
  keyspace-data:
  redis-data:

secrets:
  api_gateway_keys:
    file: ./secrets/api_gateway_keys.example
  redis_url:
    file: ./secrets/redis_url.example
  redis_password:
    file: ./secrets/redis_password.example
  puppeteer_service_token:
    file: ./secrets/puppeteer_service_token.example
